# Generated by Django 4.1.1 on 2022-10-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getintouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, null=True)),
                ('c_phone', models.IntegerField(max_length=10, null=True)),
                ('c_email', models.EmailField(max_length=254, null=True)),
                ('text', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messagebox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Message', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
